apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: options
  envs:
  - options.env
vars:
- name: EKS_CLUSTER_NAME
  objref:
    kind: ConfigMap
    name: options
    apiVersion: v1
  fieldref:
    fieldpath: data.EKS_CLUSTER_NAME
configurations:
  - env-var-transformer.yaml
resources:
- claim.yaml
